/*
 * generated by Xtext 2.12.0
 */
package org.xtext.avqscript


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AvqScriptStandaloneSetup extends AvqScriptStandaloneSetupGenerated {

	def static void doSetup() {
		new AvqScriptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
